import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import React,{act} from 'react';
const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:'http://localhost:5173'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,HTMLDialogElement:dom.window.HTMLDialogElement,IS_REACT_ACT_ENVIRONMENT:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
dom.window.scrollTo=()=>{};dom.window.matchMedia=()=>({matches:true,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return true;},media:'',onchange:null});
dom.window.HTMLCanvasElement.prototype.getContext=()=>null;
dom.window.HTMLElement.prototype.scrollIntoView=()=>{};
dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
const originalError=console.error;const errors:string[]=[];console.error=(...args:any[])=>{const message=args.join(' ');if(message.includes('Error creating WebGL context'))return;errors.push(message);};
const guestConfig={demo:true,email:false,google:false,admin:false,payments:false,lifetimeOpen:true,models:[],now:Date.now()};let user:any=null,payments:any[]=[],enabled=false;
const originalFetch=globalThis.fetch;globalThis.fetch=async(input:any)=>{const path=String(input);let data:any={};if(path.endsWith('/config'))data={...guestConfig,payments:enabled};else if(path.endsWith('/session')&&!path.includes('admin'))data={user};else if(path.endsWith('/admin/session'))data={admin:null,configured:false};else if(path.endsWith('/status'))data={services:[{name:'Database',status:'Operational',note:'Checked'},{name:'BLORP Chat',status:'Offline',note:'Not configured'}],history:[],checkedAt:Date.now(),telemetry:{memoryMb:40,processUptimeSeconds:120}};else if(path.endsWith('/payments'))data={payments};else if(path.includes('/projects'))data={projects:[]};else if(path.includes('/prompts'))data={prompts:[]};else if(path.includes('/files'))data={files:[]};else if(path.includes('/chats'))data={chats:[]};else if(path.includes('/announcements'))data={announcements:[]};return new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});};
// React DOM detects browser input support at import time; install jsdom first.
const {createRoot}=await import('react-dom/client');
const {MemoryRouter}=await import('react-router-dom');
const {default:App}=await import('../src/App.js');
const rootElement=document.getElementById('root')!;let root:ReturnType<typeof createRoot>|null=null;
async function mount(path:string){if(root)await act(async()=>root!.unmount());root=createRoot(rootElement);await act(async()=>{root!.render(React.createElement(MemoryRouter,{initialEntries:[path]},React.createElement(App)));await new Promise(r=>setTimeout(r,25));});}
test('all requested route surfaces render with an honest unconfigured state',async()=>{const routes=['/','/lab','/dashboard','/models','/playground','/experiments','/projects','/prompts','/history','/pricing','/payment?plan=pro','/developers','/status','/updates','/account','/admin','/login','/register','/verify-email','/forgot-password','/reset-password','/about','/files','/a-missing-page'];for(const route of routes){await mount(route);assert.ok(document.querySelector('main'),route+' missing main');assert.ok(document.querySelector('h1'),route+' missing heading');assert.ok(rootElement.textContent!.length>100,route+' blank');}assert.deepEqual(errors.filter(e=>!e.includes('not wrapped in act')),[]);});
test('pricing links use the exact required plan amounts',async()=>{await mount('/pricing');for(const [plan,amount] of [['core','₹100'],['pro','₹299'],['lab','₹599'],['lifetime','₹9,996']]){assert.ok(document.querySelector(`a[href="/payment?plan=${plan}"]`),plan+' link missing');assert.ok(rootElement.textContent!.includes(amount),amount+' price missing');}});
test('guests cannot see a payment QR before signing in',async()=>{await mount('/payment?plan=pro');assert.ok(rootElement.textContent!.includes('Sign in before you pay'));assert.equal(document.querySelectorAll('img[src*="upi-"]').length,0);});
test('enabled authenticated checkout maps each plan to its original QR',async()=>{user={id:'test-view-user',name:'Test Explorer',email:'viewer@example.test',verified:true,settings:{},membership:{planId:'free',expiresAt:null,activatedAt:null,status:'ACTIVE'},remaining:20};enabled=true;for(const [plan,amount] of [['core','100'],['pro','299'],['lab','599'],['lifetime','9996']]){await mount('/payment?plan='+plan);assert.equal(document.querySelector('.qr-wrapper img')?.getAttribute('src'),'/payments/upi-'+amount+'.png');assert.equal(document.querySelector('input[type=email]')?.getAttribute('value'),user.email);assert.ok(document.querySelector('input[pattern="[a-zA-Z0-9]{8,32}"]'));}user=null;enabled=false;});
test('pending checkout shows verification instead of another payment QR',async()=>{user={id:'test',name:'Explorer',email:'viewer@example.test',verified:true,settings:{},membership:{planId:'free'},remaining:20};payments=[{id:'p',plan_id:'pro',amount:299,utr:'123456789012',submitted_at:Date.now(),status:'PENDING'}];enabled=true;await mount('/payment?plan=pro');assert.ok(rootElement.textContent!.includes('PAYMENT UNDER VERIFICATION'));assert.equal(document.querySelectorAll('.qr-wrapper').length,0);user=null;payments=[];enabled=false;});
after(async()=>{if(root)await act(async()=>root!.unmount());globalThis.fetch=originalFetch;console.error=originalError;dom.window.close();});
