import express,{type Request,type Response,type NextFunction} from 'express';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import {z,ZodError} from 'zod';
import {randomBytes,createHash} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync,unlinkSync,existsSync} from 'node:fs';
import {resolve,extname,basename} from 'node:path';
import type {DatabaseSync} from 'node:sqlite';
import multer from 'multer';
import {createRemoteJWKSet,jwtVerify} from 'jose';
import type {Config} from './config.js';
import {openDatabase,transaction,type Row} from './db.js';
import {PLANS,MODELS,PROMPTS,getPlan,LIFETIME_DEADLINE} from './catalog.js';
import {id,digest,hashPassword,verifyPassword,HttpError,must,limit,guard,identity,session,createChallenge,consumeChallenge} from './security.js';
import {mailConfigured,makeMailer,type Mailer} from './mail.js';
import {membership,quota,userView,notification,submitPayment,reviewPayment,usageSummary} from './services.js';
import {chatHandler} from './chat.js';
const emailSchema=z.string().trim().toLowerCase().email().max(254),passwordSchema=z.string().min(12,'Use at least 12 characters.').max(128),nameSchema=z.string().trim().min(2).max(100);
export function createApp(config:Config,options:{db?:DatabaseSync;mailer?:Mailer;fetcher?:typeof fetch}={}){
 const db=options.db||openDatabase(config.databasePath),app=express(),mail=options.mailer||makeMailer(config),fetcher=options.fetcher||fetch;
 const emailReady=mailConfigured(config)||!!options.mailer,adminReady=!!(config.adminId&&config.adminPasswordHash&&config.adminOtpEmail&&emailReady),aiReady=!!(config.aiApiKey&&Object.values(config.modelMap).some(Boolean));
 const auth=guard(db),admin=guard(db,true);const uid=(res:Response)=>res.locals.identity.user_id as string;
 app.disable('x-powered-by');if(config.trustProxy)app.set('trust proxy',config.trustProxy);
 app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],fontSrc:["'self'",'https://fonts.gstatic.com'],imgSrc:["'self'",'blob:','data:'],connectSrc:["'self'"],objectSrc:["'none'"],frameAncestors:["'none'"],baseUri:["'self'"],formAction:["'self'"],upgradeInsecureRequests:config.production?[]:null}},crossOriginEmbedderPolicy:false,strictTransportSecurity:config.production?undefined:false}));
 app.use(cookieParser());app.use(express.json({limit:'128kb'}));
 app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');try{
  limit(db,'global:'+req.ip,500,60000);
  if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=req.get('origin');const allowed=[config.appOrigin,...(!config.production?['http://localhost:5173','http://127.0.0.1:5173']:[])];must(origin&&allowed.includes(origin),403,'Request origin not allowed.');must(req.get('sec-fetch-site')!=='cross-site',403,'Cross-site request blocked.');}
  next();}catch(e){next(e);}});
 app.get('/api/config',(_req,res)=>res.json({demo:!aiReady,google:!!(config.googleClientId&&config.googleClientSecret),email:emailReady,payments:config.paymentsEnabled&&adminReady&&aiReady&&MODELS.every(m=>!!config.modelMap[m.id]),admin:adminReady,lifetimeOpen:Date.now()<Date.parse(LIFETIME_DEADLINE),models:MODELS.filter(m=>!!config.modelMap[m.id]).map(m=>m.id),now:Date.now()}));
 app.get('/api/session',(req,res)=>{const s=identity(db,req);res.json({user:s?userView(db,s.user_id):null});});
 app.get('/api/plans',(_req,res)=>res.json({plans:PLANS,lifetimeDeadline:LIFETIME_DEADLINE}));
 const authLimit=(req:Request,email:string)=>{limit(db,'auth-ip:'+req.ip,15,900000);limit(db,'auth-subject:'+email,8,900000);};
 async function issue(email:string,purpose:string){must(emailReady,503,'Email sign-in is not configured yet. Please check back soon.');const challenge=createChallenge(db,config.sessionSecret,email,purpose);try{await mail(email,challenge.code,purpose);}catch{db.prepare('UPDATE challenges SET consumed=1 WHERE id=?').run(challenge.challengeId);throw new HttpError(503,'The verification email could not be sent. Try again later.');}return{challengeId:challenge.challengeId,message:'If this address is eligible, a code has been sent. It expires in 5 minutes.'};}
 app.post('/api/auth/register',async(req,res)=>{const data=z.object({email:emailSchema,password:passwordSchema,name:nameSchema}).parse(req.body);authLimit(req,data.email);must(emailReady,503,'Email verification is not configured yet.');const existing=db.prepare('SELECT * FROM users WHERE email=?').get(data.email) as Row|undefined;
  if(existing){res.status(202).json({challengeId:id(),message:'If this email is eligible, a verification code has been sent. If you already have an account, sign in or reset your password.'});return;}
  const userId=id(),hash=await hashPassword(data.password);db.prepare('INSERT INTO users(id,email,name,password_hash,created_at) VALUES(?,?,?,?,?)').run(userId,data.email,data.name,hash,Date.now());notification(db,userId,'Welcome to your lab','Start with a question. Save your thinking as you go.');res.status(201).json(await issue(data.email,'verify'));
 });
 app.post('/api/auth/login',async(req,res)=>{const data=z.object({email:emailSchema,password:z.string().max(128),remember:z.boolean().optional()}).parse(req.body);authLimit(req,data.email);const u=db.prepare('SELECT * FROM users WHERE email=?').get(data.email) as Row|undefined;
  const fallback='scrypt:00000000000000000000000000000000:'+('0'.repeat(128));const valid=await verifyPassword(data.password,u?.password_hash||fallback);must(valid&&u,401,'Email or password is incorrect.');if(!u!.verified){res.status(403).json({error:'Please verify your email. Use the email verification page to request a code.'});return;}session(db,res,u!.id,config.production,false,data.remember);res.json({user:userView(db,u!.id)});
 });
 app.post('/api/auth/code',async(req,res)=>{const {email,purpose}=z.object({email:emailSchema,purpose:z.enum(['login','reset','verify'])}).parse(req.body);authLimit(req,email);must(emailReady,503,'Email verification is not configured yet.');const u=db.prepare('SELECT * FROM users WHERE email=?').get(email) as Row|undefined;if(!u||(purpose==='verify'&&u.verified)){res.json({challengeId:id(),message:'If this address is eligible, a code has been sent.'});return;}res.json(await issue(email,purpose));});
 app.post('/api/auth/verify',async(req,res)=>{const data=z.object({challengeId:z.string().max(100),code:z.string().regex(/^\d{6}$/),password:passwordSchema.optional(),remember:z.boolean().optional()}).parse(req.body);limit(db,'verify-ip:'+req.ip,25,900000);
  const before=db.prepare('SELECT purpose FROM challenges WHERE id=?').get(data.challengeId) as Row|undefined;must(before?.purpose!=='admin',400,'Use the admin verification flow.');if(before?.purpose==='reset')must(data.password,400,'A new password is required.');const hash=data.password?await hashPassword(data.password):null;const c=consumeChallenge(db,config.sessionSecret,data.challengeId,data.code);const u=db.prepare('SELECT * FROM users WHERE email=?').get(c.subject) as Row|undefined;must(u,400,'Account not found.');
  if(c.purpose==='reset'){transaction(db,()=>{db.prepare('UPDATE users SET password_hash=?,verified=1 WHERE id=?').run(hash,u!.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u!.id);});}
  else db.prepare('UPDATE users SET verified=1 WHERE id=?').run(u!.id);
  session(db,res,u!.id,config.production,false,data.remember);res.json({user:userView(db,u!.id)});
 });
 app.post('/api/auth/logout',(req,res)=>{if(req.cookies.blorp_session)db.prepare('DELETE FROM sessions WHERE id_hash=?').run(digest(req.cookies.blorp_session));res.clearCookie('blorp_session',{path:'/'}).json({ok:true});});
 app.post('/api/auth/revoke-sessions',auth,(_req,res)=>{db.prepare('DELETE FROM sessions WHERE user_id=?').run(uid(res));res.clearCookie('blorp_session',{path:'/'}).json({ok:true});});
 app.get('/api/auth/google/start',(req,res)=>{must(config.googleClientId&&config.googleClientSecret,503,'Google sign-in is not configured yet.');limit(db,'google:'+req.ip,10,600000);const state=id(),verifier=randomBytes(32).toString('base64url');db.prepare('INSERT INTO challenges(id,subject,purpose,code_hash,expires_at,created_at) VALUES(?,?,?,?,?,?)').run(state,verifier,'oauth',digest(state),Date.now()+300000,Date.now());res.cookie('blorp_oauth',state,{httpOnly:true,secure:config.production,sameSite:'lax',path:'/api/auth/google',maxAge:300000});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');Object.entries({client_id:config.googleClientId,redirect_uri:config.appOrigin+'/api/auth/google/callback',response_type:'code',scope:'openid email profile',state,nonce:state,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'}).forEach(([k,v])=>url.searchParams.set(k,v));res.redirect(url.toString());});
 app.get('/api/auth/google/callback',async(req,res)=>{try{const {state,code}=z.object({state:z.string(),code:z.string()}).parse(req.query);must(req.cookies.blorp_oauth===state,400,'Invalid sign-in state.');const ch=db.prepare("SELECT * FROM challenges WHERE id=? AND purpose='oauth' AND consumed=0 AND expires_at>?").get(state,Date.now()) as Row|undefined;must(ch,400,'Sign-in expired.');db.prepare('UPDATE challenges SET consumed=1 WHERE id=?').run(state);res.clearCookie('blorp_oauth',{path:'/api/auth/google'});const r=await fetcher('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:config.googleClientId,client_secret:config.googleClientSecret,redirect_uri:config.appOrigin+'/api/auth/google/callback',grant_type:'authorization_code',code_verifier:ch!.subject}),signal:AbortSignal.timeout(15000)});must(r.ok,401,'Google sign-in failed.');const token=await r.json() as {id_token:string};const {payload}=await jwtVerify(token.id_token,createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs')),{issuer:['https://accounts.google.com','accounts.google.com'],audience:config.googleClientId});must(payload.nonce===state&&payload.email_verified===true&&payload.email&&payload.sub,401,'Google could not verify this email.');let u=db.prepare('SELECT * FROM users WHERE google_sub=? OR email=?').get(payload.sub!,String(payload.email).toLowerCase()) as Row|undefined;if(u){if(!u.verified){db.prepare('UPDATE users SET password_hash=NULL WHERE id=?').run(u.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);}must(!u.google_sub||u.google_sub===payload.sub,409,'This account uses another sign-in identity.');db.prepare('UPDATE users SET google_sub=?,verified=1 WHERE id=?').run(payload.sub!,u.id);}else{const userId=id();db.prepare('INSERT INTO users(id,email,name,google_sub,verified,created_at) VALUES(?,?,?,?,1,?)').run(userId,String(payload.email).toLowerCase(),String(payload.name||'Explorer').slice(0,100),payload.sub!,Date.now());u={id:userId};}session(db,res,u.id,config.production);res.redirect('/lab');}catch{res.redirect('/login?error=google');}});
 app.get('/api/dashboard',auth,(_req,res)=>{const userId=uid(res);res.json({user:userView(db,userId),usage:usageSummary(db,userId),quota:quota(db,userId),projects:db.prepare('SELECT * FROM projects WHERE user_id=? ORDER BY updated_at DESC').all(userId),chats:db.prepare('SELECT * FROM chats WHERE user_id=? ORDER BY updated_at DESC LIMIT 5').all(userId),files:Number((db.prepare('SELECT COUNT(*) n FROM files WHERE user_id=?').get(userId) as Row).n),prompts:Number((db.prepare('SELECT COUNT(*) n FROM saved_prompts WHERE user_id=?').get(userId) as Row).n),payments:db.prepare('SELECT * FROM payments WHERE user_id=? ORDER BY submitted_at DESC LIMIT 5').all(userId),notifications:db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 10').all(userId)});});
 app.patch('/api/account',auth,(req,res)=>{const data=z.object({name:nameSchema.optional(),settings:z.object({emailNotifications:z.boolean().optional(),compact:z.boolean().optional(),reduceMotion:z.boolean().optional()}).optional()}).parse(req.body);const u=db.prepare('SELECT * FROM users WHERE id=?').get(uid(res)) as Row;db.prepare('UPDATE users SET name=?,settings=? WHERE id=?').run(data.name||u.name,JSON.stringify({...JSON.parse(u.settings),...data.settings}),uid(res));res.json({user:userView(db,uid(res))});});
 app.get('/api/account/export',auth,(_req,res)=>{const userId=uid(res);const chats=db.prepare('SELECT * FROM chats WHERE user_id=?').all(userId) as Row[];const data={user:userView(db,userId),chats:chats.map(c=>({...c,messages:db.prepare('SELECT role,content,model,created_at FROM messages WHERE chat_id=? ORDER BY created_at').all(c.id)})),projects:db.prepare('SELECT * FROM projects WHERE user_id=?').all(userId),files:db.prepare('SELECT id,name,mime,size,created_at FROM files WHERE user_id=?').all(userId),savedPrompts:db.prepare('SELECT * FROM saved_prompts WHERE user_id=?').all(userId),payments:db.prepare('SELECT * FROM payments WHERE user_id=?').all(userId),usage:usageSummary(db,userId)};res.attachment('blorp-account-export.json').json(data);});
 app.patch('/api/notifications/:id',auth,(req,res)=>{db.prepare('UPDATE notifications SET read=1 WHERE id=? AND user_id=?').run(String(req.params.id),uid(res));res.json({ok:true});});
 app.get('/api/payments',auth,(_req,res)=>res.json({payments:db.prepare('SELECT * FROM payments WHERE user_id=? ORDER BY submitted_at DESC').all(uid(res))}));
 app.post('/api/payments',auth,(req,res)=>{must(config.paymentsEnabled&&adminReady&&aiReady&&MODELS.every(m=>!!config.modelMap[m.id]),503,'Payments are not open yet. Please wait until the lab is ready to activate memberships.');limit(db,'pay:'+uid(res),5,3600000);const d=z.object({planId:z.string(),utr:z.string().trim().regex(/^[a-zA-Z0-9]{8,32}$/,'Use the 8–32 character transaction reference from your UPI app.'),payerName:nameSchema,confirmed:z.literal(true)}).parse(req.body);res.status(201).json({payment:submitPayment(db,uid(res),d.planId,d.utr,d.payerName)});});
 app.get('/api/chats',auth,(req,res)=>{const search=String(req.query.search||'').slice(0,100),p=getPlan(membership(db,uid(res)).planId)!;const cutoff=p.historyDays?Date.now()-p.historyDays*86400000:0;res.json({chats:db.prepare('SELECT * FROM chats WHERE user_id=? AND title LIKE ? AND updated_at>=? ORDER BY updated_at DESC LIMIT 200').all(uid(res),'%'+search+'%',cutoff)});});
 const ownedChat=(chatId:string,userId:string)=>{const c=db.prepare('SELECT * FROM chats WHERE id=? AND user_id=?').get(chatId,userId) as Row|undefined;must(c,404,'Conversation not found.');const p=getPlan(membership(db,userId).planId)!;must(!p.historyDays||c!.updated_at>Date.now()-p.historyDays*86400000,403,'This conversation is outside your plan’s history window. Upgrade to restore access.');return c!;};
 app.get('/api/chats/:id',auth,(req,res)=>{const c=ownedChat(String(req.params.id),uid(res));res.json({chat:c,messages:db.prepare('SELECT * FROM messages WHERE chat_id=? ORDER BY created_at,id').all(c.id)});});
 app.patch('/api/chats/:id',auth,(req,res)=>{const c=ownedChat(String(req.params.id),uid(res)),d=z.object({title:z.string().trim().min(1).max(100)}).parse(req.body);db.prepare('UPDATE chats SET title=?,updated_at=? WHERE id=?').run(d.title,Date.now(),c.id);res.json({ok:true});});
 app.delete('/api/chats/:id',auth,(req,res)=>{ownedChat(String(req.params.id),uid(res));db.prepare('DELETE FROM chats WHERE id=? AND user_id=?').run(String(req.params.id),uid(res));res.json({ok:true});});
 app.post('/api/chat',chatHandler(db,config,fetcher));
 app.post('/api/generate',chatHandler(db,config,fetcher)); // Original route remains available, now same-origin SSE.
 const projectAccess=(userId:string)=>must(['pro','lab','lifetime'].includes(membership(db,userId).planId),403,'Projects are included with PRO and higher plans.');
 const ownedProject=(projectId:string,userId:string)=>{const p=db.prepare('SELECT * FROM projects WHERE id=? AND user_id=?').get(projectId,userId);must(p,404,'Project not found.');return p;};
 app.get('/api/projects',auth,(_req,res)=>res.json({projects:db.prepare('SELECT p.*,(SELECT COUNT(*) FROM chats c WHERE c.project_id=p.id) chats,(SELECT COUNT(*) FROM files f WHERE f.project_id=p.id) files FROM projects p WHERE user_id=? ORDER BY updated_at DESC').all(uid(res))}));
 app.post('/api/projects',auth,(req,res)=>{projectAccess(uid(res));const d=z.object({name:z.string().trim().min(1).max(80),description:z.string().max(500).default('')}).parse(req.body);must(Number((db.prepare('SELECT COUNT(*) n FROM projects WHERE user_id=?').get(uid(res)) as Row).n)<100,429,'Project limit reached.');const projectId=id();db.prepare('INSERT INTO projects(id,user_id,name,description,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(projectId,uid(res),d.name,d.description,Date.now(),Date.now());res.status(201).json({id:projectId});});
 app.get('/api/projects/:id',auth,(req,res)=>{const p=ownedProject(String(req.params.id),uid(res));res.json({project:p,chats:db.prepare('SELECT * FROM chats WHERE project_id=? AND user_id=? ORDER BY updated_at DESC').all(String(req.params.id),uid(res)),files:db.prepare('SELECT id,name,size,mime,created_at FROM files WHERE project_id=? AND user_id=?').all(String(req.params.id),uid(res))});});
 app.patch('/api/projects/:id',auth,(req,res)=>{projectAccess(uid(res));const p=ownedProject(String(req.params.id),uid(res)) as Row;const d=z.object({name:z.string().trim().min(1).max(80).optional(),description:z.string().max(500).optional(),notes:z.string().max(50000).optional()}).parse(req.body);db.prepare('UPDATE projects SET name=?,description=?,notes=?,updated_at=? WHERE id=?').run(d.name??p.name,d.description??p.description,d.notes??p.notes,Date.now(),p.id);res.json({ok:true});});
 app.delete('/api/projects/:id',auth,(req,res)=>{ownedProject(String(req.params.id),uid(res));db.prepare('DELETE FROM projects WHERE id=? AND user_id=?').run(String(req.params.id),uid(res));res.json({ok:true});});
 app.get('/api/prompts',auth,(_req,res)=>res.json({prompts:db.prepare('SELECT * FROM saved_prompts WHERE user_id=? ORDER BY favorite DESC,created_at DESC').all(uid(res))}));
 app.post('/api/prompts',auth,(req,res)=>{projectAccess(uid(res));const d=z.object({title:z.string().trim().min(1).max(100),text:z.string().min(1).max(12000),category:z.string().max(60),favorite:z.boolean().default(false)}).parse(req.body);const promptId=id();db.prepare('INSERT INTO saved_prompts VALUES(?,?,?,?,?,?,?)').run(promptId,uid(res),d.title,d.text,d.category,Number(d.favorite),Date.now());res.status(201).json({id:promptId});});
 app.patch('/api/prompts/:id',auth,(req,res)=>{const d=z.object({favorite:z.boolean()}).parse(req.body);const result=db.prepare('UPDATE saved_prompts SET favorite=? WHERE id=? AND user_id=?').run(Number(d.favorite),String(req.params.id),uid(res));must(result.changes,404,'Prompt not found.');res.json({ok:true});});
 app.delete('/api/prompts/:id',auth,(req,res)=>{db.prepare('DELETE FROM saved_prompts WHERE id=? AND user_id=?').run(String(req.params.id),uid(res));res.json({ok:true});});
 mkdirSync(config.uploadsPath,{recursive:true});const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024,files:1,fields:2}});
 app.get('/api/files',auth,(_req,res)=>res.json({files:db.prepare('SELECT id,project_id,name,mime,size,created_at FROM files WHERE user_id=? ORDER BY created_at DESC').all(uid(res))}));
 app.post('/api/files',auth,upload.single('file'),(req,res)=>{const f=req.file;must(f,400,'Choose a file.');const plan=getPlan(membership(db,uid(res)).planId)!;must(plan.uploadMb>0,403,'File uploads require CORE or higher.');must(f!.size<=plan.uploadMb*1024*1024,413,`Your plan allows files up to ${plan.uploadMb} MB.`);limit(db,'uploads:'+uid(res),30,3600000);const total=(db.prepare('SELECT COALESCE(SUM(size),0) n FROM files WHERE user_id=?').get(uid(res)) as Row).n;must(total+f!.size<=500*1024*1024,413,'Your 500 MB account storage is full. Remove files to continue.');
  let mime='text/plain';const ext=extname(f!.originalname).toLowerCase(),b=f!.buffer;const imageMime=b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':b[0]===255&&b[1]===216?'image/jpeg':b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP'?'image/webp':null;
  if(imageMime)mime=imageMime;else {must(['.txt','.md','.csv','.json','.js','.ts','.tsx','.jsx','.html','.css','.py','.yaml','.yml','.xml'].includes(ext)&&!b.includes(0),415,'Supported: text, Markdown, CSV, JSON, code, PNG, JPG and WebP. PDF extraction is not available yet.');}
  const projectId=req.body.projectId?String(req.body.projectId):null;if(projectId){projectAccess(uid(res));ownedProject(projectId,uid(res));}const fileId=id(),storageKey=id();writeFileSync(resolve(config.uploadsPath,storageKey),b,{mode:0o600});try{db.prepare('INSERT INTO files VALUES(?,?,?,?,?,?,?,?)').run(fileId,uid(res),projectId,basename(f!.originalname).slice(0,200),mime,f!.size,storageKey,Date.now());}catch(e){unlinkSync(resolve(config.uploadsPath,storageKey));throw e;}res.status(201).json({file:{id:fileId,name:basename(f!.originalname),mime,size:f!.size}});
 });
 app.get('/api/files/:id',auth,(req,res)=>{const f=db.prepare('SELECT * FROM files WHERE id=? AND user_id=?').get(String(req.params.id),uid(res)) as Row|undefined;must(f,404,'File not found.');res.set('Content-Type','application/octet-stream');res.download(resolve(config.uploadsPath,f!.storage_key),f!.name);});
 app.delete('/api/files/:id',auth,(req,res)=>{const f=db.prepare('SELECT * FROM files WHERE id=? AND user_id=?').get(String(req.params.id),uid(res)) as Row|undefined;must(f,404,'File not found.');db.prepare('DELETE FROM files WHERE id=? AND user_id=?').run(f!.id,uid(res));try{unlinkSync(resolve(config.uploadsPath,f!.storage_key));}catch{}res.json({ok:true});});
 app.get('/api/admin/session',(req,res)=>res.json({admin:identity(db,req,true)?.admin_id||null,configured:adminReady}));
 app.post('/api/admin/login',async(req,res)=>{must(adminReady,503,'Admin access requires an admin ID, password hash and working email configuration.');const d=z.object({id:z.string().max(100),password:z.string().max(128)}).parse(req.body);limit(db,'admin-ip:'+req.ip,5,900000);limit(db,'admin-id:'+d.id,5,900000);const valid=await verifyPassword(d.password,config.adminPasswordHash);must(d.id===config.adminId&&valid,401,'Admin ID or password is incorrect.');const c=createChallenge(db,config.sessionSecret,config.adminOtpEmail,'admin');try{await mail(config.adminOtpEmail,c.code,'admin');}catch{throw new HttpError(503,'The admin verification email could not be sent.');}res.cookie('blorp_preauth',c.challengeId,{httpOnly:true,secure:config.production,sameSite:'strict',path:'/api/admin',maxAge:300000});res.json({challengeId:c.challengeId});});
 app.post('/api/admin/verify',(req,res)=>{const d=z.object({challengeId:z.string().max(100),code:z.string().regex(/^\d{6}$/)}).parse(req.body);limit(db,'admin-verify:'+req.ip,15,900000);must(req.cookies.blorp_preauth===d.challengeId,403,'Start with your admin ID and password.');const before=db.prepare("SELECT * FROM challenges WHERE id=? AND purpose='admin' AND subject=?").get(d.challengeId,config.adminOtpEmail);must(before,400,'Invalid admin verification.');consumeChallenge(db,config.sessionSecret,d.challengeId,d.code);session(db,res,config.adminId,config.production,true);res.clearCookie('blorp_preauth',{path:'/api/admin'}).json({admin:config.adminId});});
 app.post('/api/admin/resend',async(req,res)=>{must(adminReady,503,'Admin not configured.');const old=req.cookies.blorp_preauth;const c=old?db.prepare("SELECT * FROM challenges WHERE id=? AND purpose='admin' AND consumed=0 AND attempts<5 AND expires_at>?").get(old,Date.now()) as Row|undefined:null;must(c,401,'Enter your admin credentials again.');limit(db,'admin-resend:'+req.ip,5,900000);const next=createChallenge(db,config.sessionSecret,config.adminOtpEmail,'admin');await mail(config.adminOtpEmail,next.code,'admin');res.cookie('blorp_preauth',next.challengeId,{httpOnly:true,secure:config.production,sameSite:'strict',path:'/api/admin',maxAge:300000}).json({challengeId:next.challengeId});});
 app.post('/api/admin/logout',(req,res)=>{if(req.cookies.blorp_admin)db.prepare('DELETE FROM sessions WHERE id_hash=?').run(digest(req.cookies.blorp_admin));res.clearCookie('blorp_admin',{path:'/'}).json({ok:true});});
 app.get('/api/admin/overview',admin,(_req,res)=>{const users=db.prepare('SELECT id,email,name,verified,created_at FROM users ORDER BY created_at DESC LIMIT 1000').all() as Row[];const members=users.map(u=>({...u,membership:membership(db,u.id),quota:quota(db,u.id)}));const payments=db.prepare('SELECT p.*,u.email,u.name FROM payments p JOIN users u ON p.user_id=u.id ORDER BY submitted_at DESC LIMIT 1000').all() as Row[];const totals=db.prepare("SELECT COUNT(*) payments,COALESCE(SUM(CASE WHEN status='APPROVED' THEN amount ELSE 0 END),0) revenue,COALESCE(SUM(CASE WHEN status='APPROVED' AND reviewed_at>=? THEN amount ELSE 0 END),0) monthlyRevenue,SUM(status='PENDING') pending FROM payments").get(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),1));res.json({users:members,payments,totals,usage:usageSummary(db),plans:PLANS,announcements:db.prepare('SELECT * FROM announcements ORDER BY published_at DESC').all(),audit:db.prepare('SELECT * FROM audit_log ORDER BY created_at DESC LIMIT 50').all(),configuration:{email:emailReady,google:!!config.googleClientId,ai:aiReady,payments:config.paymentsEnabled&&aiReady&&adminReady,database:true},totalUsers:Number((db.prepare('SELECT COUNT(*) n FROM users').get() as Row).n)});});
 app.post('/api/admin/payments/:id/review',admin,(req,res)=>{const d=z.object({action:z.enum(['APPROVED','REJECTED']),note:z.string().max(500).default(''),bankChecked:z.boolean().optional()}).parse(req.body);must(d.action==='REJECTED'||d.bankChecked,400,'Confirm that you checked the amount and UTR in your bank or UPI app.');res.json({payment:reviewPayment(db,String(req.params.id),res.locals.identity.admin_id,d.action,d.note)});});
 app.post('/api/admin/announcements',admin,(req,res)=>{const d=z.object({title:z.string().trim().min(1).max(120),body:z.string().trim().min(1).max(2000)}).parse(req.body);const announcementId=id();db.prepare('INSERT INTO announcements VALUES(?,?,?,?,?)').run(announcementId,d.title,d.body,Date.now(),res.locals.identity.admin_id);res.status(201).json({id:announcementId});});
 app.delete('/api/admin/announcements/:id',admin,(req,res)=>{db.prepare('DELETE FROM announcements WHERE id=?').run(String(req.params.id));res.json({ok:true});});
 app.get('/api/announcements',(_req,res)=>res.json({announcements:db.prepare('SELECT id,title,body,published_at FROM announcements ORDER BY published_at DESC LIMIT 10').all()}));
 let lastHealth=0;app.get('/api/status',(_req,res)=>{const t=performance.now();let database=true;try{db.prepare('SELECT 1').get();}catch{database=false;}const services=[...['Chat','Code','Vision','Research'].map(name=>{const key=name==='Chat'?'fast':name.toLowerCase();return{name:'BLORP '+name,status:aiReady&&config.modelMap[key]?'Degraded':'Offline',note:aiReady&&config.modelMap[key]?'Configured · live provider health not monitored':'AI connection not configured'};}),{name:'Authentication',status:emailReady?'Operational':'Offline',note:emailReady?'Sign-in service configured':'Email delivery not configured'},{name:'Database',status:database?'Operational':'Offline',note:'Checked on this request'},{name:'Payment Verification',status:config.paymentsEnabled&&adminReady&&aiReady&&MODELS.every(m=>!!config.modelMap[m.id])?'Operational':'Offline',note:config.paymentsEnabled&&adminReady&&aiReady&&MODELS.every(m=>!!config.modelMap[m.id])?'Manual review by administrator':'Payments not open'}];
  if(database&&Date.now()-lastHealth>60000){lastHealth=Date.now();for(const s of services)db.prepare('INSERT INTO health_samples(service,status,latency_ms,checked_at) VALUES(?,?,?,?)').run(s.name,s.status,s.name==='Database'?Math.round(performance.now()-t):null,Date.now());db.prepare('DELETE FROM health_samples WHERE checked_at<?').run(Date.now()-90*86400000);}
  res.json({services,checkedAt:Date.now(),history:database?db.prepare("SELECT strftime('%Y-%m-%d',checked_at/1000,'unixepoch') day,service,SUM(status='Operational') operational,COUNT(*) samples FROM health_samples GROUP BY day,service ORDER BY day DESC LIMIT 630").all():[],telemetry:{memoryMb:Math.round(process.memoryUsage().rss/1024/1024),processUptimeSeconds:Math.round(process.uptime()),gpu:null,coreLoad:null}});
 });
 app.use('/api',(_req,res)=>res.status(404).json({error:'This API endpoint does not exist.'}));
 if(existsSync(resolve('dist/index.html'))){app.use(express.static(resolve('dist'),{maxAge:3600000}));app.get('/{*path}',(_req,res)=>res.sendFile(resolve('dist/index.html')));}
 app.use((e:any,_req:Request,res:Response,_next:NextFunction)=>{if(res.headersSent){res.end();return;}const status=e instanceof ZodError?400:e instanceof HttpError?e.status:e instanceof multer.MulterError?413:500;res.status(status).json({error:e instanceof ZodError?e.issues.map(i=>i.message).join(' '):status===500?'The request could not be completed. Please try again.':e.message});if(status===500)console.error('Request failed:',e instanceof Error?e.message:'Unknown error');});
 return{app,db};
}
