import {useEffect,useState,lazy,Suspense} from 'react';
import {Link,useLocation,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowRight,Mail,ShieldCheck,ArrowLeft,KeyRound} from 'lucide-react';
import {Brand,ErrorNotice,Tag} from '../components/UI';
import {post,useApp} from '../lib/api';
const Core=lazy(()=>import('../components/Core'));
export default function Auth(){const {pathname}=useLocation();const [params]=useSearchParams();const register=pathname==='/register',reset=pathname==='/forgot-password'||pathname==='/reset-password',verify=pathname==='/verify-email';const [method,setMethod]=useState<'password'|'code'>('password'),[email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(false),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(0);const {config,user,refresh}=useApp(),navigate=useNavigate();const next=params.get('next')?.startsWith('/')&&!params.get('next')?.startsWith('//')?params.get('next')!:'/lab';
 useEffect(()=>{setChallenge('');setCode('');setError('');setPassword('');},[pathname]);useEffect(()=>{if(user&&!reset&&!verify)navigate(next,{replace:true});},[user]);useEffect(()=>{if(!cooldown)return;const t=setTimeout(()=>setCooldown(c=>c-1),1000);return()=>clearTimeout(t);},[cooldown]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(challenge){await post('/auth/verify',{challengeId:challenge,code,...(reset?{password}:{}),remember});await refresh();navigate(next);return;}if(register){const r=await post('/auth/register',{name,email,password});setChallenge(r.challengeId);setCooldown(60);}else if(reset||verify||method==='code'){const r=await post('/auth/code',{email,purpose:reset?'reset':verify?'verify':'login'});setChallenge(r.challengeId);setCooldown(60);}else{await post('/auth/login',{email,password,remember});await refresh();navigate(next);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function resend(){setError('');setBusy(true);try{const r=await post('/auth/code',{email,purpose:reset?'reset':verify||register?'verify':'login'});setChallenge(r.challengeId);setCooldown(60);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="auth-page"><section className="auth-visual"><div className="eyebrow">// A NEW SPACE FOR YOUR NEXT IDEA</div><h1>ENTER A<br/>DIFFERENT<br/><span>STATE OF MIND.</span></h1><div className="auth-core"><Suspense fallback={null}><Core compact/></Suspense></div><div className="auth-visual-footer"><span>BLORP AI LAB / 2026</span><span>ENGINEERED FOR CURIOSITY.</span></div></section><section className="auth-form-panel"><Link to="/" className="back-link"><ArrowLeft size={14}/> Back to BLORP</Link><div className="auth-form-inner"><Tag>{challenge?'CHECK YOUR INBOX':register?'CREATE YOUR ACCOUNT':reset?'ACCOUNT RECOVERY':verify?'EMAIL VERIFICATION':'WELCOME BACK'}</Tag><h2>{challenge?'A little verification.':register?'Your lab awaits.':reset?'Let’s get you back in.':verify?'Verify your email.':'Good to see you.'}</h2><p>{challenge?`Enter the 6-digit code sent to ${email}. It expires in 5 minutes.`:register?'Bring your ideas. We’ll make room for them.':reset?'We’ll send a code to reset your password.':verify?'Request a new code to confirm your email address.':'Sign in to pick up where you left off.'}</p>
 {!challenge&&!reset&&!verify&&<><a className={'google-button '+(!config.google?'unavailable':'')} href={config.google?'/api/auth/google/start':undefined} aria-disabled={!config.google} onClick={e=>{if(!config.google)e.preventDefault();}}><span className="google-letter">G</span>Continue with Google{!config.google&&<small>Not configured</small>}</a><div className="auth-divider"><span>or continue with email</span></div>{!register&&<div className="segmented"><button className={method==='password'?'active':''} onClick={()=>setMethod('password')}>Password</button><button className={method==='code'?'active':''} onClick={()=>setMethod('code')}>Email code</button></div>}</>}
 <form onSubmit={submit}>{challenge?<><label>Verification code<input className="otp-field" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000" required autoFocus/></label>{reset&&<label>New password<input type="password" autoComplete="new-password" minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 12 characters" required/></label>}</>:<>{register&&<label>Your name<input value={name} autoComplete="name" minLength={2} maxLength={100} onChange={e=>setName(e.target.value)} placeholder="What should we call you?" required/></label>}<label>Email address<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label>{(register||!reset&&!verify&&method==='password')&&<label>Password<input type="password" autoComplete={register?'new-password':'current-password'} value={password} minLength={register?12:undefined} maxLength={128} onChange={e=>setPassword(e.target.value)} placeholder={register?'At least 12 characters':'Enter your password'} required/></label>}{!reset&&!verify&&<div className="auth-options"><label className="checkbox-label"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Remember me</label>{!register&&<Link to="/forgot-password">Forgot password?</Link>}</div>}</>}
 <ErrorNotice message={params.get('error')==='google'?'Google sign-in could not be completed. Try email sign-in or retry Google.':''}/>{error&&<ErrorNotice message={error}/>}{!config.email&&(register||method==='code'||verify||reset)&&<div className="notice">Email verification is not configured yet. You can explore the lab in demo mode.</div>}<button className="button full" disabled={busy||!config.email&&(register||method==='code'||verify||reset)}>{busy?'Please wait…':challenge?reset?'Reset password':'Verify & continue':register?'Create account':reset||verify||method==='code'?'Send verification code':'Sign in'}<ArrowRight size={16}/></button>
 </form>{challenge?<div className="auth-resend"><button disabled={cooldown>0||busy} onClick={resend}>{cooldown?`Resend in ${cooldown}s`:'Resend code'}</button><button onClick={()=>{setChallenge('');setCode('');}}>Use a different email</button></div>:<div className="auth-bottom">{reset||verify?<Link to="/login">Back to sign in</Link>:register?<>Already have an account? <Link to="/login">Sign in</Link></>:<>New to the lab? <Link to="/register">Create an account</Link></>}{!register&&!reset&&!verify&&<Link to="/verify-email">Need to verify your email?</Link>}</div>}<Link to="/lab" className="explore-demo">Explore demo <ArrowRight size={14}/></Link><div className="auth-security"><ShieldCheck size={14}/> Your work. Your workspace.</div></div></section></div>;}
