import {lazy,Suspense,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Play,Plus,ArrowUp,Code2,Eye,Brain,Sparkles,ChevronDown,Activity} from 'lucide-react';
import {SectionHeading,Tag} from '../components/UI';
import {LineChart,Bars,ReasoningGraph} from '../components/Charts';
import {useApp} from '../lib/api';
const Core=lazy(()=>import('../components/Core'));
export default function Home(){const {config}=useApp();const [prompt,setPrompt]=useState(''),[mode,setMode]=useState('reason');const navigate=useNavigate();const modes=[['Reason',Brain,'reason'],['Code',Code2,'code'],['Vision',Eye,'vision'],['Research',Sparkles,'research']] as const;return <>
 <section className="home-hero"><div className="hero-grid-lines" aria-hidden="true"/><div className="hero-topline"><span><i/> EXPERIMENTAL AI LABORATORY</span><span>EST. 2026 <span className="slash">/</span> VERSION 0.3</span></div><div className="hero-copy"><div className="hero-release"><span className="release-square"/>THE NEXT CHAPTER OF INTELLIGENCE <ArrowUpRight size={13}/></div><h1>INTELLIGENCE,<br/><span>ENGINEERED.</span></h1><p>A living laboratory for your biggest ideas.<br/>Build, test and create with intelligence that<br className="desktop-only"/> moves you forward.</p><div className="hero-buttons"><Link to="/lab" className="button">Enter the lab <ArrowUpRight size={18}/></Link><button className="button ghost" onClick={()=>document.getElementById('inside-system')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}><span className="play-circle"><Play size={12} fill="currentColor"/></span>Explore the system</button></div><div className="hero-meta"><span>HUMAN IDEAS.</span><span>MACHINE INTELLIGENCE.</span><span>A BETTER TOMORROW.</span></div></div><div className="hero-core"><Suspense fallback={<div className="core-loading">INITIALIZING VISUAL CORE…</div>}><Core/></Suspense><div className="core-caption"><span>NEURAL ENGINE — 001</span><span>INTERACTIVE 3D <Plus size={12}/></span></div><div className="core-coordinate">X 028.49<br/>Y 071.08<br/><span>PROCEDURAL SCENE</span></div></div><div className="hero-bottom"><span>SCROLL TO DISCOVER <span className="scroll-line"/></span><span>NOTHING ORDINARY. EVERYTHING POSSIBLE. <Plus size={14}/></span></div></section>
 <section className="home-command-wrap"><form className="home-command" onSubmit={e=>{e.preventDefault();navigate('/lab?prompt='+encodeURIComponent(prompt)+'&mode='+mode);}}><div className="command-input"><span className="command-mark">✳</span><input aria-label="Ask BLORP" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="An idea starts here. Ask BLORP anything…"/><button className="send-button" aria-label="Open prompt in lab"><ArrowUp size={19}/></button></div><div className="command-options"><div className="model-caption"><span className="model-cube"/>BLORP Core <ChevronDown size={13}/></div><div>{modes.map(([name,Icon,id])=><button type="button" key={id} className={mode===id?'mode-chip active':'mode-chip'} onClick={()=>setMode(id)}><Icon size={13}/>{name}</button>)}</div></div></form><div className="command-note"><span>ONE WORKSPACE. EVERY WAY YOU THINK.</span><Tag tone={config.demo?'amber':''}>{config.demo?'DEMO MODE · TRY THE INTERFACE':'CONNECTED AI EXPERIENCE'}</Tag></div></section>
 <div className="home-stats"><div><strong>08</strong><span>BLORP MODEL PROFILES</span></div><div><strong>09</strong><span>EXPERIMENTS TO EXPLORE</span></div><div><strong>01</strong><span>CONNECTED WORKSPACE</span></div><div><strong>∞</strong><span>POSSIBLE STARTING POINTS</span></div></div>
 <section className="home-section" id="inside-system"><SectionHeading index="01" title="Your mind. Amplified." link="Inside the lab" to="/lab"/><div className="capability-layout"><Link to="/lab" className="capability conversation"><div className="capability-top"><Tag>CONVERSATIONAL INTELLIGENCE</Tag><ArrowUpRight/></div><h3>Good questions.<br/>Extraordinary possibilities.</h3><p>Follow a thought further. Explore a new angle.<br/>Make complex ideas feel clear.</p><div className="conversation-art"><div><span className="mini-avatar">Y</span>What if we approached it differently?</div><div><span className="mini-avatar blue">B</span><div><i/><i/><i/></div></div><span className="art-caption">ILLUSTRATIVE CONVERSATION</span></div></Link><Link to="/lab?mode=code" className="capability code"><div className="capability-top"><Tag>CODE GENERATION</Tag><Code2/></div><div className="code-art"><div><span>01</span><b>const</b> future = <em>await</em></div><div><span>02</span>　blorp.<b>create</b>({'{'}</div><div><span>03</span>　　idea: <em>"something new"</em>,</div><div><span>04</span>　　possibilities: <em>Infinity</em></div><div><span>05</span>　{'}'});</div></div><h3>Less friction.<br/>More building.</h3><p>Write, review and debug with a capable coding partner.</p></Link><Link to="/lab?mode=vision" className="capability vision"><div className="capability-top"><Tag>VISION & MULTIMODAL</Tag><Eye/></div><div className="vision-art" aria-hidden="true"><div className="viewfinder"><div className="scanline"/><svg viewBox="0 0 220 90"><path d="M15 62L55 35l45 24 39-43 65 43M15 62l85 15 104-18M55 35l45 42 39-61" fill="none" stroke="#6587b2"/><g fill="#99c9ff"><circle cx="15" cy="62" r="3"/><circle cx="55" cy="35" r="3"/><circle cx="100" cy="59" r="3"/><circle cx="139" cy="16" r="3"/><circle cx="204" cy="59" r="3"/></g></svg></div></div><h3>See beyond the surface.</h3><p>Turn images into understanding.</p></Link><Link to="/lab?mode=reason" className="capability reasoning"><div className="capability-top"><Tag>DEEP REASONING</Tag><Brain/></div><ReasoningGraph/><h3>Complexity, connected.</h3><p>Bring structure to your hardest questions.</p></Link></div><div className="capability-strip"><Link to="/lab?mode=creative"><Sparkles size={20}/><span>Creative generation<small>Give the unexpected a chance.</small></span><ArrowUpRight/></Link><Link to="/lab?mode=research"><Activity size={20}/><span>Research & analysis<small>Build a clearer picture.</small></span><ArrowUpRight/></Link></div></section>
 <section className="home-section lab-showcase"><div className="showcase-copy"><div className="eyebrow">02 / A WORKSPACE THAT THINKS WITH YOU</div><h2>Not just a chat.<br/><span>Your entire lab.</span></h2><p>Projects, prompts, models and experiments. Everything you need to go from “what if” to what’s next.</p><Link className="button secondary" to="/dashboard">Explore your workspace <ArrowUpRight size={17}/></Link><div className="showcase-index"><span>01 / ORGANIZE</span><span>02 / EXPERIMENT</span><span>03 / BUILD</span></div></div><div className="showcase-console"><div className="console-top"><span>BLORP_ / SYSTEM OVERVIEW</span><Tag>INTERFACE PREVIEW</Tag></div><div className="console-middle"><div><small>WORKSPACE ACTIVITY</small><strong>A clearer perspective.</strong><LineChart values={[8,15,12,28,21,34,28,37,30,51,46,63,53,75,68,85]} label="Illustrative activity preview" height={110}/></div><div className="console-side"><span>TOKEN FLOW</span><Bars values={[4,7,5,10,8,14,11,16,13,18]} label="Illustrative token chart"/></div></div><div className="console-bottom"><span>PROJECTS <b>Bring your ideas together</b></span><span>HISTORY <b>Pick up your thinking</b></span></div><p className="sample-note">Illustrative preview. Your dashboard shows your actual usage.</p></div></section>
 <section className="home-section final-invitation"><div className="eyebrow">03 / YOUR NEXT GREAT IDEA STARTS HERE</div><h2>Curiosity is<br/>only the beginning.</h2><Link to="/lab" className="button">Make something extraordinary <ArrowUpRight size={19}/></Link><Link to="/pricing" className="text-link">Find your access level <ArrowRight size={16}/></Link><div className="invitation-wordmark" aria-hidden="true">BLORP_</div></section>
 </>;}
