import {useEffect,useRef,useState} from 'react';
import {Link,NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,Command,Search,X,Menu,Plus,MessageSquare,Code2,Eye,Brain,Folder,Clock,Bookmark,BarChart3,SlidersHorizontal,BookOpen,Files,Settings,ChevronDown,FlaskConical,LayoutDashboard,Shield,LogOut} from 'lucide-react';
import {Brand,Tag} from './UI';
import {post,useApp} from '../lib/api';
const routes=[['AI Lab','/lab',MessageSquare],['Dashboard','/dashboard',LayoutDashboard],['Models','/models',Brain],['Playground','/playground',SlidersHorizontal],['Experiments','/experiments',FlaskConical],['Projects','/projects',Folder],['Prompt Library','/prompts',Bookmark],['History','/history',Clock],['Files','/files',Files],['Pricing','/pricing',BarChart3],['Settings','/account',Settings],['Documentation','/developers',BookOpen]] as const;
export function Layout(){const {user,config,loading,connectionError}=useApp();const {pathname}=useLocation();const [menu,setMenu]=useState(false),[palette,setPalette]=useState(false),[query,setQuery]=useState('');const dialog=useRef<HTMLDialogElement>(null);const navigate=useNavigate();
 useEffect(()=>{setMenu(false);window.scrollTo(0,0);document.title=pathname==='/'?'BLORP AI LAB — Intelligence, engineered.':`${routes.find(r=>r[1]===pathname)?.[0]||pathname.split('/')[1].replaceAll('-',' ')} — BLORP AI LAB`;},[pathname]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v);}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(palette){dialog.current?.showModal();}else dialog.current?.close();},[palette]);
 return <><a className="skip-link" href="#main">Skip to content</a><header className="top-nav"><div className="nav-inner"><Brand/><nav className={menu?'public-nav open':'public-nav'} aria-label="Main navigation">{[['Lab','/lab'],['Models','/models'],['Playground','/playground'],['Experiments','/experiments'],['Developers','/developers'],['Pricing','/pricing'],['About','/about']].map(([n,p])=><NavLink to={p} key={p}>{n}</NavLink>)}</nav><div className="nav-actions"><button className="icon-button search-trigger" onClick={()=>setPalette(true)} aria-label="Search pages, Control K"><Search size={18}/></button>{user?<Link to="/account" className="avatar" aria-label="Your account">{user.name[0].toUpperCase()}</Link>:<Link className="nav-signin" to="/login">Sign in</Link>}<Link className="button small nav-cta" to="/lab">Enter lab<ArrowUpRight size={15}/></Link><button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></div></header>
 {connectionError&&<div className="connection-notice" role="alert">Connection unavailable. Please refresh to reconnect.</div>}
 <main id="main" tabIndex={-1}><Outlet/></main>
 <footer className="site-footer"><div><Brand/><span>Human ideas. Machine intelligence.</span></div><nav aria-label="Footer"><Link to="/status">System status</Link><Link to="/updates">Changelog</Link><Link to="/developers">Docs</Link><Link to="/admin">Admin</Link></nav><div className="footer-bottom"><span>© {new Date().getFullYear()} BLORP AI LAB</span><span>{loading?'CONNECTING':config.demo?'DEMO MODE · AI NOT CONNECTED':'AI CONNECTION CONFIGURED'}</span><span>BUILT FOR WHAT’S NEXT ↗</span></div></footer>
 <dialog ref={dialog} className="command-dialog" onClose={()=>{setPalette(false);setQuery('');}} onClick={e=>{if(e.target===e.currentTarget)setPalette(false);}}><div className="command-search"><Search size={20}/><input aria-label="Search commands" placeholder="Where do you want to go?" value={query} onChange={e=>setQuery(e.target.value)} autoFocus/><button className="keycap" onClick={()=>setPalette(false)}>esc</button></div><div className="command-results">{routes.filter(r=>r[0].toLowerCase().includes(query.toLowerCase())).map(([name,path,Icon])=><button key={path} onClick={()=>{navigate(path);setPalette(false);}}><Icon size={17}/>{name}<ArrowRight size={15}/></button>)}</div><div className="command-foot"><Command size={13}/> Navigate your laboratory</div></dialog></>;
}
export function Workspace(){const {user,config,refresh}=useApp();const [open,setOpen]=useState(false);const location=useLocation();useEffect(()=>setOpen(false),[location]);return <div className="workspace"><button className="workspace-toggle" onClick={()=>setOpen(!open)}><Menu size={17}/> Workspace <ChevronDown size={15}/></button><aside className={'workspace-sidebar '+(open?'show':'')}><div className="sidebar-label">PERSONAL WORKSPACE <span>01</span></div><Link to="/lab?new=1" className="new-chat"><Plus size={18}/>New chat <span>↗</span></Link><nav aria-label="Workspace"><div className="sidebar-label">WORKSPACE</div>{routes.slice(0,2).map(([n,p,I])=><NavLink key={p} to={p}><I size={17}/>{n}</NavLink>)}{[['Code','code',Code2],['Vision','vision',Eye],['Research','research',Brain]].map(([n,mode,I])=>{const Icon=I as typeof Code2;return <Link key={String(mode)} to={`/lab?mode=${mode}`}><Icon size={17}/>{String(n)}</Link>;})}<div className="sidebar-divider"/>{routes.slice(3,9).map(([n,p,I])=><NavLink key={p} to={p}><I size={17}/>{n}</NavLink>)}<div className="sidebar-divider"/><NavLink to="/developers"><BookOpen size={17}/>API access <span className="tiny-tag">BETA</span></NavLink><NavLink to="/account"><Settings size={17}/>Settings</NavLink></nav><div className="sidebar-plan"><div><span className="eyebrow">YOUR ACCESS</span><Tag>{user?.membership.planId.toUpperCase()||'EXPLORER'}</Tag></div><p>{user?`${user.remaining.toLocaleString()} messages left today`:'A new space for your next idea.'}</p><Link to="/pricing">Explore plans<ArrowUpRight size={15}/></Link></div><div className="sidebar-profile"><span className="avatar">{user?.name[0]?.toUpperCase()||'B'}</span><div><strong>{user?.name||'Lab explorer'}</strong><small>{config.demo?'Demo environment':'Personal workspace'}</small></div>{user&&<button aria-label="Sign out" className="icon-button" onClick={async()=>{await post('/auth/logout');await refresh();}}><LogOut size={16}/></button>}</div></aside><div className="workspace-content"><div className="workspace-topline"><span><span className="slash">/</span> WORKSPACE <span className="slash">/</span> {location.pathname.split('/')[1].toUpperCase()}</span><div><Tag tone={config.demo?'amber':''}>{config.demo?'DEMO MODE':'AI CONNECTED'}</Tag><span className="desktop-only">BLORP v0.3</span></div></div><Outlet/></div></div>;}
